spring:
  profiles:
    active:
      - dev

  application:
    name: "lprakashv-blog"

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  thymeleaf:
    cache: false

  devtools:
    livereload:
      enabled: true


---
spring:
  profiles: prod

  datasource:
    url: ${MYAPP_JDBC_URL}
    username: "postgres"
    password: "rootpassword"
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    initialize: true
    dbcp2:
      validation-query: 'select 1'
      fast-fail-validation: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect


---
spring:
  profiles: dev

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url=jdbc:h2: file:/data/demo